apiVersion: v1
baseDomain: example.com 
compute: 
- hyperthreading: Enabled 
  name: worker
  replicas: 0 
controlPlane: 
  hyperthreading: Enabled 
  name: master
  replicas: 3 
metadata:
  name: pruthvi 
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14 
    hostPrefix: 23 
  networkType: OVNKubernetes 
  serviceNetwork: 
  - 172.30.0.0/16
platform:
  none: {} 
fips: false 
pullSecret: '{"auths":{"bastion.pruthvi.example.com:8443":{"auth": "<< encrypted password from quay login"}}}'
sshKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDGkvwaA7rdjnziSf+tSPW7tyAK9f4ywre7ZZLsN/Z9MuP+zguBsCjtUHoeIWCIa7D7e0nq1Y6a5S4Vxrwx42TsPUHLNVq2V7FJbFHO24JlqNrVwUUBnPXne88H6jmVMUDL4gxMwvLe85CD72jrZhcDB7LqdZdEDH4viMfl2LPPqe2O5gntjNPNpDMuP1l/pbnkNAy6LWHgVvkwx9fhlnitV8Iq05D1Jp3/f1SGQBYldATY1Taw4n+iyyK0JD87Qc6gZsuhdBu/AvTdMZJWkVA6Ft874jaf9L3y/CJNqyusXhWatCIHueebO6ZRlv9Uyl/hQvGKPMQyXPZaiAaUU5yIc55LkAezGV013DQcXtZWI+YkbWc3AiEjfQKP7oOD0mQHW6BNU2w/UoTCaTsDefbJQgiiHMOyS2y/HmCe0q4M38KqjWUmRiMLUr24g6xbBtsdaPM2JhKmApLvMl8jtRQwk+hXsOjPrJdovryO64Cy42vqv4mY/xPWHjr+o8jdCVU= root@bastion.pruthvi.example.com'
additionalTrustBundle: |
  -----BEGIN CERTIFICATE-----
    #### Copy file from  cat ../registry/quay-rootCA/rootCA.pem ####
  -----END CERTIFICATE-----
imageContentSources:
- mirrors:
  - bastion.pruthvi.example.com:8443/ocp4.11/openshift4.11
  source: quay.io/openshift-release-dev/ocp-release
- mirrors:
  - bastion.pruthvi.example.com:8443/ocp4.11/openshift4.11
  source: quay.io/openshift-release-dev/ocp-v4.0-art-dev
